# Generated by Django 5.1.1 on 2024-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='views',
            field=models.CharField(max_length=50),
        ),
    ]
