# Generated by Django 5.1.1 on 2024-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
